sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t evandam93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true evandam93/react-test npm test

after_success:
  - docker build -t evandam93/multi-client ./client
  - docker build -t evandam93/multi-nginx ./nginx
  - docker build -t evandam93/multi-server ./server
  - docker build -t evandam93/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push evandam93/multi-client
  - docker push evandam93/multi-nginx
  - docker push evandam93/multi-server
  - docker push evandam93/multi-worker