sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t evandam93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true evandam93/react-test npm test

after_success:
  - docker build -t evandam93/multi-client ./client
  - docker build -t evandam93/multi-nginx ./nginx
  - docker build -t evandam93/multi-server ./server
  - docker build -t evandam93/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push evandam93/multi-client
  - docker push evandam93/multi-nginx
  - docker push evandam93/multi-server
  - docker push evandam93/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-096007086684"
  bucket_path: "multi-docker"
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on:
    branch: master